/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const __wbg_game_free: (a: number, b: number) => void;
export const game_new: (a: number, b: number) => [number, number, number];
export const game_update: (a: number, b: number) => [number, number];
export const game_render: (a: number) => [number, number];
export const game_handle_key_input: (a: number, b: number, c: number) => [number, number];
export const game_handle_mouse_input: (a: number, b: number, c: number, d: number, e: number) => [number, number];
export const start: () => void;
export const initialize_game: (a: number, b: number) => [number, number, number];
export const __wbg_gameinstance_free: (a: number, b: number) => void;
export const gameinstance_new: (a: number, b: number) => [number, number, number];
export const gameinstance_connect_to_server: (a: number, b: number, c: number) => [number, number];
export const gameinstance_disconnect_from_server: (a: number) => [number, number];
export const gameinstance_get_connection_state: (a: number) => [number, number];
export const gameinstance_update: (a: number) => number;
export const gameinstance_render: (a: number) => void;
export const gameinstance_handle_key_event: (a: number, b: number) => [number, number];
export const gameinstance_handle_mouse_event: (a: number, b: number, c: number, d: number, e: number, f: number) => void;
export const gameinstance_dispose: (a: number) => void;
export const wasm_logger_init: () => void;
export const __wbindgen_exn_store: (a: number) => void;
export const __externref_table_alloc: () => number;
export const __wbindgen_export_2: WebAssembly.Table;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_export_6: WebAssembly.Table;
export const __externref_table_dealloc: (a: number) => void;
export const closure2_externref_shim: (a: number, b: number, c: any) => void;
export const closure94_externref_shim: (a: number, b: number, c: any) => void;
export const __wbindgen_start: () => void;
