[package]
name = "ecs_derive"
version = "0.1.0"
edition = "2021"
authors = ["ECS Wasm Game Developer"]
description = "Derive macros for ECS Wasm Game"

[lib]
proc-macro = true

[dependencies]
syn = { version = "2.0", features = ["full"] }
quote = "1.0"
proc-macro2 = "1.0" 